{% set name = "timg" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/timg-{{ version }}.tar.gz
  sha256: 938d939ac3502300f7b9e3daadf5da0f88c5b86fde5882d73b43a9d028bd4bfd

build:
  entry_points:
    - timg = timg.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - pillow
    - python {{ python_min }}
    - setuptools
  run:
    - pillow
    - python >={{ python_min }}

test:
  imports:
    - timg
  commands:
    - pip check
    - timg --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adzierzanowski/timg
  summary: print an image in terminal
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
